# use an existing image as a base 
FROM node:alpine

##COPY the build files
WORKDIR /app

COPY package.json .

# Download and install a dependency
RUN npm install
COPY . .



#Tell the image what to do when it starts as a container
CMD ["npm","run","start"]
